"""new fileds in user model

Revision ID: 76267d6c4843
Revises: 25df7668d501
Create Date: 2022-03-14 18:00:12.837472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76267d6c4843'
down_revision = '25df7668d501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
